name: gallery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^9.0.0
  path_provider: ^2.1.5
  path: 1.9.0
  mime: ^2.0.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  chewie: ^1.10.0
  video_player: ^2.9.2
  video_player_win: ^3.1.1
  flutter_vlc_player: ^7.4.2
  audioplayers: ^6.2.0
  file_icon: ^1.0.0
  intl: ^0.20.2
  exif: ^3.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
